name: ThrottleInputApp 2
language: nodejs
variables:
  - name: throttle
    inputType: OutputTopic
    description: ''
    defaultValue: throttle-input
    required: false
  - name: bearer_token
    inputType: Secret
    description: ''
    defaultValue: bearer_token
    required: true
dockerfile: src/build/dockerfile
defaultFile: src/app/services/quix.service.ts
