name: ICE Model
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: hello-world-source
    required: true
  - name: input
    inputType: InputTopic
    description: ''
    defaultValue: ice-input
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
